apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeU1ERXpNREV4TURjME5Wb1hEVE15TURFeU9URXhNRGMwTlZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSmNXCmZDUHZ5N0YrYmp4MFRCZ0xocWo3UDI3R0p0VW11OURhc2ZTN0JNR1lQWGRuNXNUdThyQWFQWXQ1RXpKWHlZTnIKVGJjbVIxbXpZZGlST284R2RReGUxaS91SmxrSGhtcENpbVFEYkJOWlBxd1JadXZPaHFiTUpQQ0lTbm1jeWZtNwpUaFlOaUEzdzdkUE00aG1wT2FHcWdSK1RRRVRmdFJZd1ZZc25TSElZaFlVV3NocVloTGg4bVdjaWNRZk5XcG5SCmhaVk13VVgrU1E4Z2dvaVgzOFpnL0N5M2NUZU5yQ1c3QndnM3g3NWdpemY4dkFLZGZlUDZkTHV1Rm9CQjIzYzMKcFIyd0RpTVJvM2FvSUltY1VtSDREc2Eycm9PV29sWmZCNWV2alFqTmFNTGY5NHBqcXJyWnc3NzNiWUVhRTU5Qgp5dXpERlE1TmZwS3RKN05LeUJNQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJSSUE2SzBsL3U1ZWFVRlZJOFVPK1NRWW5pQ3dqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFKdlRpa2plVgp6SnEyWmkydlF6SmtXRDlodTdnQTRieGhTSUV5UURtZTkwUXRXTWI1VFJTWksvVDIzYWI2RlJtN045UzkrbG1rCjhycS91Sk80ZXRqYkZUNnpnUE1tekZjMXYzZFRCZVNwZlJxSlpjb0p0aFFKTHdMQlVHd2JnMkk4bG5tSlRsZXIKUk14SDRNWlI1NVk4VVJVMWJEcHJzTmtmMnlnSjJlcVo3cGZKT1pkTGdyY0lDWEt0aHdnOThtY1lIYzRSbVl4eQpKZHFyMGVkUVFJeFRKd2VQMTlrUGlQVWdvTlZ6Y0cwT1haV3NJNUd5NTJOeFA1YWNpQnJyaDFpcGlpN0pMQ2dICkZSMnpwVW8ySjRmNS9SRTdjVHNSZlZlVnlvZHk4K1hOWWg4V3JGMmM4RjVoQ3hTektpSmQ5aEIvN3RtSHJPVFIKNmZhWnowL3pHQVJaNVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: Z3Vlc3Rib29r
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklqaDVhVzltU0c5MmFUQndXVXhPYjB0MVRFOVliRjlNVWpOeWVDMVZTekpmWTNZMWRtRllkbWQwY3pnaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpuZFdWemRHSnZiMnNpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxZM0psZEM1dVlXMWxJam9pWkdWbVlYVnNkQzEwYjJ0bGJpMW5PSE51YXlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKa1pXWmhkV3gwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pTXpCbE4yWXpOR1l0WWpJM01pMDBaREpsTFdFek5ESXRPR00xTXpjd1pHUmpOVGRtSWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tZDFaWE4wWW05dmF6cGtaV1poZFd4MEluMC5pZzVMd01SOGtKX0FlQkVxUmJTTzliaWpSOXV3Z043X1pzV0hLcGhXWGNDYk5pYVhwbWw1THhLNUctemVVQXRsLWdvaWREbm15bWJXUERnTkllZGc2c25DRWRGT3RVTWpzeDFCUEUtdHdQOTR4X1VjVS1HTnNzZ1U0SHB1Q3RXNnQzeEh6SUlvNDVjcm5rWGwza25FS1ppelZFWVo3bzQwSDA5NGNhZk5xeXRPR1JwU2Nyb1hrZUF5X0pnRVViYmU0LTQtLTJ3VmFpNWIxN3ZXbG4tMndOX0ZHSDhoN2lXa0xZRGV3QkhqaFJhQWJVUmlDZHAzSVloZk5CTms0NF9UcTJRMW9PSTI3YUhhN0J0MnZVYS0yRlpXMVFOdjhGU0NjOHJLUlZwTEpkb3NITU9TRHpQNWNrRHlScE1GZ1p3QVdTcEJXU0tZOVJjc043MHNDbzRrMnc=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 30e7f34f-b272-4d2e-a342-8c5370ddc57f
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-31T20:07:28Z"
  name: default-token-g8snk
  namespace: guestbook
type: kubernetes.io/service-account-token
